### ISSUE TITLE
How to deal with trimmed reads?

### ISSUE THREAD

**Issue by xflicsu** [YangLab/bamTobw#2]
Hello Xiao-Ou,
      You write a useful tool to convert bam to bw format.
      I have two questions:
         1. How to deal with trimmed reads (the length of each sequence is not equal)?
         2. Is this tool suitable for both SE and PE sequencing data sets?

**Comment by kepbod** [comment]
> 1. How to deal with trimmed reads (the length of each sequence is not equal)?

The read length is only used in calculating HPB (-s). If you want to use trimmed reads to calculate HPB, you could assign an average read length to it (I will add this function later).


> 2. Is this tool suitable for both SE and PE sequencing data sets?

Yes, this tool suitable for both SE and PE sequencing data sets.The BigWig file did not rely on sequencing type.
